### PR TITLE
make grid color configurable

### LINKED ISSUE #89: Allow option for grid color
Here, https://github.com/yaronn/blessed-contrib/blob/master/lib/layout/grid.js#L32. Please make the color configurable :smile:

### PR DESCRIPTION
**Pull request by mhsjlw**
fixes #89

### CODE REVIEW

**Comment by theforcedk** [comment]
Please merge all these goodies that people have created

**Comment by yaronn** [comment]
Cool! Sorry for the late merge.

**Comment by yaronn** [comment]
Thanks @theforcedk for pinging me, I dropped the ball here due to work load.

**Comment by theforcedk** [comment]
@yaronn No worries, work is important :) - I just use this repo as a remote dependency and this PR + the vi bindings for the list is exactly the hacks I had to make locally.

**Pull request merged**
