### PR TITLE
build(dependencies): upgrade dependencies

### PR DESCRIPTION
**Pull request by lirantal**
Upgrading old deps which are outdated and include security vulnerabilities either directly or through nested deps of their own.

### CODE REVIEW

**Comment by binarymist** [comment]
Thanks @lirantal .. Can we please have this merged ASAP?

**Comment by lirantal** [comment]
@binarymist I don't have commit rights on this repo (or on the npm package).
pinging @yaronn 🙏

**Comment by lirantal** [comment]
Yep.

**Comment by binarymist** [comment]
Thanks @yaronn, will this be published to npm in the near future?

**Pull request merged**
